### ISSUE TITLE
进群

### ISSUE THREAD

**Issue by FightingChu** [sxuya/summary_BeyondFeelings#1]
请问进群收费吗？如果不收费的话，可以拉我进群吗？谢谢啦

**Comment by sxuya** [comment]
> 请问进群收费吗？如果不收费的话，可以拉我进群吗？谢谢啦

有群费的（RMB2000 左右的 BTC（比特币）），主要是给群主，也是进群前操作数字货币的入门操作熟悉。如果觉得进群费太贵，你可以再考虑一下。

请问你有没有看《定投改变命运》的书呢？如果没看，就一定先看，不然进来你也不知道在讲什么。

另外一个事前了解，就是在「Mixin」这个 app 里面搜索 7000102093，进入公开课的群里面先了解一些简单的内容。

我的 Mixin ID 是：37360540，欢迎来沟通。

我是认为这群费很值，除了投资的心理建设（李笑来主讲）（其他群不会有投资心理建设的，仔细想想这个有多重要），目前还有「编程课」、「逻辑课」、「写作课」、「英语课」、「销售课」。每个课程在外面单独学习，价格可能都不止这个价格吧。课程内容也帮我度过了今年艰难的半年。

**Comment by FightingChu** [comment]
哦哦哦，那这样的话，其实我也在里面，哈哈哈。
